name: Scan repo and pull requests for Credentials with Gitleaks

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    name: Scan for secrets using Gitleaks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --redact --verbose --exit-code 1
